/* Calculator.java */
/* Generated By:JavaCC: Do not edit this line. Calculator.java */
package edu.wallawalla.cs.cptr354.visitor;

import static org.junit.Assert.assertEquals;
import java.io.StringReader;
import org.junit.Test;

public class CalculatorTests {
	ExpressionParser parser = new ExpressionParser(new StringReader(""));
	
	@Test
	public void testAddition() throws Exception {
		String inputString = "a = 5 + 6;" + System.lineSeparator();
		String result = ConsoleInterceptor.copyOut(() -> {
			parser.ReInit(new StringReader(inputString));
			ASTstart expr = parser.start();
			ExpressionVisitor v = new ExpressionVisitor();
			System.out.println(expr.jjtAccept(v, null));
		});
		assertEquals("{a=11}" + System.lineSeparator(), result);
	}

	@Test
	public void testSubtraction() throws Exception {
		String inputString = "b = 5 - 6;" + System.lineSeparator();
		String result = ConsoleInterceptor.copyOut(() -> {
			parser.ReInit(new StringReader(inputString));
			ASTstart expr = parser.start();
			ExpressionVisitor v = new ExpressionVisitor();
			System.out.println(expr.jjtAccept(v, null));
		});
		assertEquals("{b=-1}" + System.lineSeparator(), result);
	}

	@Test
	public void testMultiplication() throws Exception {
		String inputString = "c = 5 * 6;" + System.lineSeparator();
		String result = ConsoleInterceptor.copyOut(() -> {
			parser.ReInit(new StringReader(inputString));
			ASTstart expr = parser.start();
			ExpressionVisitor v = new ExpressionVisitor();
			System.out.println(expr.jjtAccept(v, null));
		});
		assertEquals("{c=30}" + System.lineSeparator(), result);
	}

	@Test
	public void testDivision() throws Exception {
		String inputString = "d = 12 / 6;" + System.lineSeparator();
		String result = ConsoleInterceptor.copyOut(() -> {
			parser.ReInit(new StringReader(inputString));
			ASTstart expr = parser.start();
			ExpressionVisitor v = new ExpressionVisitor();
			System.out.println(expr.jjtAccept(v, null));
		});
		assertEquals("{d=2}" + System.lineSeparator(), result);
	}

}
